# Generated by Django 4.2.13 on 2024-06-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(help_text='the language in which the book is written', max_length=100),
        ),
    ]
